%YAML:1.0
---
IMU.Machine.Middle.Angle: -0.821
Axis0.Can.ID: 0x010
Axis1.Can.ID: 0x020
# Remember to open set the two parmas [true] in the real system run time
# And set the DJI [S1==3](in the middle)
Debug.Momentum.Wheel: 1
Debug.Back.Drive.Wheel: 1

# Servo Config
Servo.Port.Name: "/dev/ttyUSB3"
Servo.ID: 0
Servo.BaudRate: 115200

Dbus.Serial.Port.Name: "/dev/dbus_serial"
Imu.Serial.Port.Name: "/dev/imu_serial"